// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDguDnH9M69Of8curDshGOPZXoiXoeSym0',
    appId: '1:946710770661:web:89006858de7237fdbc750c',
    messagingSenderId: '946710770661',
    projectId: 'travel-app-29cfc',
    authDomain: 'travel-app-29cfc.firebaseapp.com',
    storageBucket: 'travel-app-29cfc.firebasestorage.app',
    measurementId: 'G-PPRVVZ46TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBwxhiYJdTMY0qkgfhzqwudyFwKsoy0pU',
    appId: '1:946710770661:android:3563eedb951cfb64bc750c',
    messagingSenderId: '946710770661',
    projectId: 'travel-app-29cfc',
    storageBucket: 'travel-app-29cfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEgPhX7DlVBvBxdKTVqv2LhPAyfwI9N2A',
    appId: '1:946710770661:ios:6d0feca54c236ba9bc750c',
    messagingSenderId: '946710770661',
    projectId: 'travel-app-29cfc',
    storageBucket: 'travel-app-29cfc.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEgPhX7DlVBvBxdKTVqv2LhPAyfwI9N2A',
    appId: '1:946710770661:ios:6d0feca54c236ba9bc750c',
    messagingSenderId: '946710770661',
    projectId: 'travel-app-29cfc',
    storageBucket: 'travel-app-29cfc.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDguDnH9M69Of8curDshGOPZXoiXoeSym0',
    appId: '1:946710770661:web:cb41b0b5d72b1980bc750c',
    messagingSenderId: '946710770661',
    projectId: 'travel-app-29cfc',
    authDomain: 'travel-app-29cfc.firebaseapp.com',
    storageBucket: 'travel-app-29cfc.firebasestorage.app',
    measurementId: 'G-RYKLS9QBXH',
  );
}
